const ProductsList = [
  {
    num: "01",
    name: "MxTrade",
    detail:
      "This is a centralized crypto trading terminal with 350+ feature-rich back office panels where a variety of methods are owned by the admin. It allows to settle trades between peers using a central order book for utility tokens, reward tokens, and security tokens to ensure seamless transactions.",
    link1: "",
    link2: "",
    img: "/assets/images/MxTrade.png",
    btnc: "linear-gradient(to right, #F27E63 50%, transparent 50%)",
    border: "1px solid #F27E63",
    color: "#F27E63",
    highlight: "USP:- Dynamic Scaling Engines",
    question: "Who can benefit?",
    tags: "New coin owners | Banks | Exchanges | Traders | FX Brokers | Community Marketers ",
  },
  {
    num: "02",
    name: "MxFuture",
    detail:
      "Open up new investment avenues with a leverage-based centralized trading environment designed for institutional traders and high-risk appetite retail audiences. It has features such as 100x spot leverage trade, perpetual swaps, inverse futures, American options, and European options.",
    link1: "",
    link2: "",
    img: "/assets/images/MxFuture.png",
    btnc: "linear-gradient(to right, #00ACD7 50%, transparent 50%)",
    border: "1px solid #00ACD7",
    highlight: "USP: VaR (Value at Risk) based Risk Engines",
    question: "Who can benefit?",
    tags: "Institutional traders | Hedge funds | Family office | Banks | Tier 2-3 exchanges | Forex platform owners",
    color: "#00ACD7",
  },
  {
    num: "03",
    name: "MxDex",
    detail:
      "A complete blockchain-driven trading platform with smart contracts matches direct peers and settles orders on the blockchain for utility tokens and DeFi tokens without involving third parties and institutionalized control. With features such as 9 Blockchain support, a Blockchain bridge, and an inbuilt liquidity pool for optimal user experience.",
    link1: "",
    link2: "",
    img: "/assets/images/MxDex.png",
    btnc: "linear-gradient(to right, #F2AB27 50%, transparent 50%)",
    border: "1px solid #F2AB27",
    highlight: "USP: Highly Scalable, Modular and Secure Implementations ",
    question: "Who can benefit?",
    tags: "Coin Owners | DAOs (Decentralized autonomous organizations) | DeFi Projects",
    color: "#F2AB27",
  },
  {
    num: "04",
    name: "MxFi",
    detail:
      "Creating a digital ecosystem of decentralized finance using decentralized blockchain networks for lending, stacking, borrowing, lotteries, farming, etc. Additionally, it supports all smart contracts and private EVM chains to deliver a wide array of services without fraudulent activities.",
    link1: "",
    link2: "",
    img: "/assets/images/MxFI.png",
    btnc: "linear-gradient(to right, #4BA6A6 50%, transparent 50%)",
    border: "1px solid #4BA6A6",
    highlight: "USP: Transparency of Transactions",
    question: "Who can benefit?",
    tags: "Coin Owners | DAOs (Decentralized autonomous organizations) | DeFi Projects",
    color: "#4BA6A6",
  },
  {
    num: "05",
    name: "MxLaunch",
    detail:
      "An all blockchain-supported fundraising platform for Utility, DeFi, Security, and NFT Tokens with various models like IEO, IDO, IGO, and STOs. Boost crowdfunding opportunities with customized centralized and decentralized fundraising dashboards and a bonus and discount setup.",
    link1: "",
    link2: "",
    img: "/assets/images/MxLaunch.png",
    btnc: "linear-gradient(to right, #9E9BF2 50%, transparent 50%)",
    border: "1px solid #9E9BF2",
    highlight: "USP: A KYC/AML Compliant Dashboard",
    question: "Who can benefit?",
    tags: "New coin owners | Exchanges | FX brokers | Banks | Traders | Community marketers | DAO | DeFi Projects | VC firms",
    color: "#9E9BF2",
  },
  {
    num: "06",
    name: "MxWallet",
    detail:
      "Based on a modular architecture setup, its use case includes a hot multi-sig centralized wallet and an all blockchain-compatible decentralized wallet. Enables users to Hold, Swap, and Invest in their favorite utility, DeFi, or reward tokens with payment gateway integration.",
    link1: "",
    link2: "",
    img: "/assets/images/MxWallet.png",
    btnc: "linear-gradient(to right, #BF9A78 50%, transparent 50%)",
    border: "1px solid #BF9A78",
    highlight: "USP: 180+ crypto support",
    question: "Who can benefit?",
    tags: "New coin owners | Exchanges | FX brokers | Banks | Traders | Community marketers | DAO | DeFi Projects | VC firms",
    color: "#BF9A78",
  },
  {
    num: "07",
    name: "MxBlock",
    detail:
      "A customized Layer 1 and Layer 2 blockchain use case designed for specific niche needs and tokenizes any asset over the private network of setup blockchain. For professional investors, the Blockchain Consensus setup and enhanced layered security facilitate efficient transactions.",
    link1: "",
    link2: "",
    img: "/assets/images/MxBlock.png",
    btnc: "linear-gradient(to right, #4B99FF 50%, transparent 50%)",
    border: "1px solid #4B99FF",
    highlight: "USP: Private Blockchain and Consensus Modeling",
    question: "Who can benefit?",
    tags: "New coin owners | FX brokers | Traders | Community marketers | DAO | DeFi Projects | VC firms",
    color: "#4B99FF",
  },
  {
    num: "08",
    name: "MxNFT",
    detail:
      "An all blockchain compatible NFT suite infused with cutting-edge technology for the creation, auction, and trading of all non-fungible tokens within a single platform over any EVM public chain or private chain allows creators, collectors, and dealers to benefit from liquid investments. This complete 8+ use case implemented template saves you from unnecessary development time and cost.",
    link1: "",
    link2: "",
    img: "/assets/images/MxNFT.png",
    btnc: "linear-gradient(to right, #D95276 50%, transparent 50%)",
    border: "1px solid #D95276",
    highlight: "USP: Enterprise Ready with full Suit Customizations",
    question: "Who can benefit?",
    tags: "Artist group | Cultural importance organizations  | Sports franchise owners | FMCG brands",
    color: "#D95276",
  },
];
export default ProductsList;
