const ProductsList = [
  {
    num: "01",
    name: "MxTrade",
    detail:
      "A centralized crypto trading terminal with a wide range of methods and platform features owned by the admin. Utility Tokens, Reward Tokens, and Security Tokens are settled using a central order book between peers. This solution helps New coin owners, Exchanges, FX brokers, Banks, Traders, and community marketers.",
    link1: "",
    link2: "",
    img: "/assets/images/MxTrade.png",
    btnc: "linear-gradient(to right, #F08270 50%, transparent 50%)",
    border: "1px solid #F08270",
    color: "#F08270",
    highlight: "USP:- Dynamic Scaling Engines",
    question: "Platform Benefits",
    tags: "New coin owners | Banks | Exchanges | Traders | FX Brokers | Community Marketers ",
    sublist: [
      "200K Transaction per second match engine",
      "Instant settlement",
      "Multi-sig hot wallet",
      "350+ feature rich backoffice panel",
    ],
  },
  {
    num: "02",
    name: "MxFuture",
    detail:
      "Open up new investment avenues with a leverage-based centralized trading environment designed for institutional traders and high-risk appetite retail audiences. It has features such as 100x spot leverage trade, perpetual swaps, inverse futures, American options, and European options.",
    link1: "",
    link2: "",
    img: "/assets/images/MxFuture.png",
    btnc: "linear-gradient(to right, #C3B091 50%, transparent 50%)",
    border: "1px solid #C3B091",
    highlight: "USP: VaR (Value at Risk) based Risk Engines",
    question: "Platform Benefits",
    tags: "Institutional traders | Hedge funds | Family office | Banks | Tier 2-3 exchanges | Forex platform owners",
    color: "#C3B091",
    sublist: [
      "100x leverage engine",
      "Auto Deleveraging (ADL) calculator",
      "Value at Risk (VaR) engine",
      "Portfolio margining",
      "Easy to set up contracts",
    ],
  },
  {
    num: "03",
    name: "MxDex",
    detail:
      "A complete blockchain-driven trading platform with smart contracts matches direct peers and settles orders on the blockchain for utility tokens and DeFi tokens without involving third parties and institutionalized control. With features such as 9 Blockchain support, a Blockchain bridge, and an inbuilt liquidity pool for optimal user experience.",
    link1: "",
    link2: "",
    img: "/assets/images/MxDex.png",
    btnc: "linear-gradient(to right, #0E88F5 50%, transparent 50%)",
    border: "1px solid #0E88F5",
    highlight: "USP: Highly Scalable, Modular and Secure Implementations ",
    question: "Platform benefits",
    tags: "Coin Owners | DAOs (Decentralized autonomous organizations) | DeFi Projects",
    color: "#0E88F5",
    sublist: [
      "9 blockchain support",
      " Blockchain bridge setup",
      "In-built liquidity pool",
      " Private EVM chain support",
    ],
  },
  {
    num: "04",
    name: "MxFi",
    detail:
      "Creating a digital ecosystem of decentralized finance using decentralized blockchain networks for lending, stacking, borrowing, lotteries, farming, etc. Additionally, it supports all smart contracts and private EVM chains to deliver a wide array of services without fraudulent activities.",
    link1: "",
    link2: "",
    img: "/assets/images/MxFI.png",
    btnc: "linear-gradient(to right, #9A9A9A 50%, transparent 50%)",
    border: "1px solid #9A9A9A",
    highlight: "USP: Transparency of Transactions",
    question: "Platform benefits",
    tags: "Coin Owners | DAOs (Decentralized autonomous organizations) | DeFi Projects",
    color: "#9A9A9A",
    sublist: [
      "9 blockchain support",
      " Blockchain bridge setup",
      "In-built liquidity pool",
      " Private EVM chain support",
      "All smart contract support",
    ],
  },
  {
    num: "05",
    name: "MxLaunch",
    detail:
      "An all blockchain-supported fundraising platform for Utility, DeFi, Security, and NFT Tokens with various models like IEO, IDO, IGO, and STOs. Boost crowdfunding opportunities with customized centralized and decentralized fundraising dashboards and a bonus and discount setup.",
    link1: "",
    link2: "",
    img: "/assets/images/MxLaunch.png",
    btnc: "linear-gradient(to right, #D22544 50%, transparent 50%)",
    border: "1px solid #D22544",
    highlight: "USP: A KYC/AML Compliant Dashboard",
    question: "Platform benefits",
    tags: "New coin owners | Exchanges | FX brokers | Banks | Traders | Community marketers | DAO | DeFi Projects | VC firms",
    color: "#D22544",
    sublist: [
      " Centralized fundraising dashboard ",
      " Decentralized fundraising dashboard  ",
      " Bonus and Discount setup ",
      " All blockchain support  ",
    ],
  },
  {
    num: "06",
    name: "MxWallet",
    detail:
      "Based on a modular architecture setup, its use case includes a hot multi-sig centralized wallet and an all blockchain-compatible decentralized wallet. Enables users to Hold, Swap, and Invest in their favorite utility, DeFi, or reward tokens with payment gateway integration.",
    link1: "",
    link2: "",
    img: "/assets/images/MxWallet.png",
    btnc: "linear-gradient(to right, #394F18 50%, transparent 50%)",
    border: "1px solid #394F18",
    highlight: "USP: 180+ crypto support",
    question: "Platform benefits",
    tags: "New coin owners | Exchanges | FX brokers | Banks | Traders | Community marketers | DAO | DeFi Projects | VC firms",
    color: "#394F18",
    sublist: [
      " Hot Multi-Sig Centralized wallet ",
      " All blockchain compatible Decentralized wallet      ",
      " Merchant Payment enabled ",
      " Open API for payment gateway integrations  ",
      " Use-case based modular Architecture setup   ",
    ],
  },
  {
    num: "07",
    name: "MxBlock",
    detail:
      "A customized Layer 1 and Layer 2 blockchain use case designed for specific niche needs and tokenizes any asset over the private network of setup blockchain. For professional investors, the Blockchain Consensus setup and enhanced layered security facilitate efficient transactions.",
    link1: "",
    link2: "",
    img: "/assets/images/MxBlock.png",
    btnc: "linear-gradient(to right, background: #7945EF 50%, transparent 50%)",
    border: "1px solid background: #7945EF",
    highlight: "USP: Private Blockchain and Consensus Modeling",
    question: "Platform benefits",
    tags: "New coin owners | FX brokers | Traders | Community marketers | DAO | DeFi Projects | VC firms",
    color: "background: #7945EF",
    sublist: [
      " Custom blockchain consensus setup ",
      " Tokenize any asset class      ",
      " Enhance layered security ",
      " Complete control on project ownership and roadmap  ",
    ],
  },
  {
    num: "08",
    name: "MxNFT",
    detail:
      "An all blockchain compatible NFT suite infused with cutting-edge technology for the creation, auction, and trading of all non-fungible tokens within a single platform over any EVM public chain or private chain allows creators, collectors, and dealers to benefit from liquid investments. This complete 8+ use case implemented template saves you from unnecessary development time and cost.",
    link1: "",
    link2: "",
    img: "/assets/images/MxNFT.png",
    btnc: "linear-gradient(to right, #C34CB8 50%, transparent 50%)",
    border: "1px solid #C34CB8",
    highlight: "USP: Enterprise Ready with full Suit Customizations",
    question: "Platform benefits",
    tags: "Artist group | Cultural importance organizations  | Sports franchise owners | FMCG brands",
    color: "#C34CB8",
    sublist: [
      " End-to-end journey within one platform ",
      " Custom control for royalty      ",
      " All blockchain support  ",
      " 8+ use case implemented template  ",
    ],
  },
];
export default ProductsList;
